version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    network_mode: "host"

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: "task:1:1"
    network_mode: "host"

  kafka-producer-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kafka-producer-service
    environment:
      SPRING_KAFKA_BOOTSTRAP-SERVERS: localhost:9092
    ports:
      - "8080:8080"
    restart: always
    network_mode: "host"